{"name": "test_number_of_days_data_check", "status": "failed", "statusDetails": {"message": "AssertionError: assert 5 == 4\n  -5\n  +4", "trace": "self = <weather_forecast.test_london.TestLondon object at 0x04224910>\n\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_number_of_days_data_check(self):\n        global request\n        response = requests.get(self.request)\n        response_body = response.json()\n        count = len(response_body[\"list\"])\n        list1 = []\n        for i in range(count):\n            date_time = response_body[\"list\"][i][\"dt_txt\"]\n            date = date_time.split(\" \")[0]\n            if date not in list1:\n                list1.append(date)\n>       assert len(list1) == 4\nE       assert 5 == 4\nE         -5\nE         +4\n\nweather_forecast\\test_london.py:27: AssertionError"}, "start": 1589454039074, "stop": 1589454040518, "uuid": "dfa76f88-667b-4eb7-9bb9-5bb81cc0b660", "historyId": "6690b923a41b854b32c5d900f3180493", "testCaseId": "6f0083f3ddc4a17115e234fe9b4ab31a", "fullName": "weather_forecast.test_london.TestLondon#test_number_of_days_data_check", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "weather_forecast"}, {"name": "suite", "value": "test_london"}, {"name": "subSuite", "value": "TestLondon"}, {"name": "host", "value": "INLT370"}, {"name": "thread", "value": "29996-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "weather_forecast.test_london"}]}